version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/init-project/templates/profiles/typescript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/init-project/templates/profiles/go"
    schedule:
      interval: "weekly"
